# Generated by Django 5.2.10 on 2026-02-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
