# Generated by Django 5.2.10 on 2026-03-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttranslation",
            name="seo_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="producttranslation",
            name="seo_title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
