name: Django CI

on:
  push:
    branches: ["main", "develop"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: brand_media_db
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: 123456

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_NAME: brand_media_db
      DB_USER: admin
      DB_PASSWORD: 123456
      DB_HOST: postgres
      DB_PORT: 5432
      DJANGO_SETTINGS_MODULE: core.settings.dev

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          cd brand-media-platform-be
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          cd brand-media-platform-be
          python manage.py migrate

      - name: Run tests
        run: |
          cd brand-media-platform-be
          python manage.py test